import type { Space } from '@abf/shared';
import type { SentryEvent, SentryIssue } from './sentry.js';

export function formatPullRequestTitle(
  issue: SentryIssue,
  issueIdPrefix: string,
): string {
  return `auto-fix(sentry-${issueIdPrefix}): ${issue.title}`;
}

export function formatPullRequestBody(
  space: Space,
  issue: SentryIssue,
  event: SentryEvent,
): string {
  const exception = event.exception?.values?.[0];
  const errorLine =
    exception?.type && exception?.value
      ? `${exception.type}: ${exception.value}`
      : (exception?.value ?? exception?.type ?? issue.title);

  const eventLink = eventPermalink(space, issue, event);

  const lines: string[] = [];
  lines.push(`Auto-fix for Sentry Issue [${issue.shortId}](${issue.permalink})`);
  lines.push('');
  lines.push(`**Error:** ${errorLine}`);
  lines.push(`**Occurrences:** ${issue.count}`);
  lines.push(`**First seen:** ${issue.firstSeen}`);
  lines.push(`**Last seen:** ${issue.lastSeen}`);
  if (event.environment) lines.push(`**Environment:** ${event.environment}`);
  if (event.release) lines.push(`**Release:** ${event.release}`);
  if (eventLink) lines.push(`**Last event:** [view](${eventLink})`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('Generated by auto-bug-fixer. Review carefully before merging.');
  return lines.join('\n');
}

function eventPermalink(
  space: Space,
  issue: SentryIssue,
  event: SentryEvent,
): string | undefined {
  const eventId = event.eventID ?? event.id;
  if (!eventId) return undefined;
  return `${space.sentryBaseUrl}/organizations/${space.sentryOrgSlug}/issues/${issue.id}/events/${eventId}/`;
}
